# Homebrew formula for corpus-forge — deployed to ``ulmentflam/homebrew-tap``.
#
# Deploy by copying this file to ``Formula/corpus-forge.rb`` in the tap
# repo (``https://github.com/ulmentflam/homebrew-tap``). On each release,
# bump ``url`` to the new tag tarball and ``sha256`` to its digest
# (``shasum -a 256``). A release-CI job can automate this with
# ``brew bump-formula-pr``.
#
# Install:
#   brew install ulmentflam/tap/corpus-forge
#
# Upgrade (corpus-forge ``update`` subcommand auto-detects the brew
# channel and runs this for you):
#   brew upgrade corpus-forge
#
# Install path mirrors install.sh / the nightly formula. corpus-forge's
# dependency closure includes ``sentence-transformers`` -> ``torch``, which
# has no buildable sdist, so Homebrew's ``virtualenv_install_with_resources``
# (pip-from-sdists) can't drive it. We ``uv sync --frozen`` the bundled
# uv.lock into a venv under libexec instead, then shim into bin/. The
# project's uv.lock pins CPU-only torch (see its pyproject ``[tool.uv]``
# block), so the Linux bottle stays lean. torch publishes no x86_64-macOS
# wheel, so the formula targets Apple Silicon on macOS.
class CorpusForge < Formula
  desc "Forge a living, trainable corpus from notes, code, and chat history"
  homepage "https://github.com/ulmentflam/corpus-forge"
  url "https://github.com/ulmentflam/corpus-forge/archive/refs/tags/v0.1.0b17.tar.gz"
  # Update this on each release. ``shasum -a 256 corpus-forge-<version>.tar.gz``
  sha256 "37f4c7a9a01671023a8b0e6cd2aff46ff6857181ed988dbed7505bd0dcc27317"
  license "Apache-2.0"
  head "https://github.com/ulmentflam/corpus-forge.git", branch: "main"

  depends_on "python@3.12"
  depends_on "uv"
  on_macos do
    depends_on arch: :arm64
  end

  def install
    # Materialize the venv from the bundled (CPU-torch) uv.lock under
    # libexec — see the header for why uv drives this instead of
    # `virtualenv_install_with_resources`.
    libexec.install Dir["*"], Dir[".[!.]*"]
    cd libexec do
      system "uv", "sync", "--frozen"
    end

    # Shim into bin/. `--frozen --no-sync`: the venv was materialized
    # above and the installed tree under libexec is read-only, so uv must
    # NOT re-resolve (writes uv.lock) or re-sync (writes .venv) at runtime
    # — either fails with "Operation not permitted" in the Cellar.
    (bin/"corpus-forge").write <<~SHIM
      #!/bin/bash
      # Auto-generated by the Homebrew formula. Mirror of install.sh's path.
      # Source: #{libexec}
      exec uv run --project "#{libexec}" --frozen --no-sync --quiet corpus-forge "$@"
    SHIM
    chmod 0755, bin/"corpus-forge"
  end

  test do
    # Smoke: --version prints a reasonable string.
    assert_match "corpus-forge version", shell_output("#{bin}/corpus-forge --version")
    # Smoke: doctor exits 0 on a fresh install (config will be WARN
    # but doctor's healthy invariant tolerates WARN for that check).
    system "#{bin}/corpus-forge", "doctor"
  end
end
